9 processo de design
Interacao-Humano-Computador/2021.1-Prefeitura-de-Concordia pull request #12
Opened 2021-08-12 12:49 UTC by Abraao1231

## Descrição
- Adição do documento de processo de design 

## Está consertando alguma issue aberta?
- Sim, o PR está relacionado a issue #9 

## Tarefas gerais realizadas
Adicione aqui as tarefas realizadas
- Adição do documento de processo de design
- Escolha do processo de design que será utilizado no projeto

2021-08-12 13:30 UTC, Joao-Moura requested changes
Acho que o documento pode ser detalhado um pouco mais, além de incluir o porque da utilização desse processo de design (ex.: [SEI](https://interacao-humano-computador.github.io/2020.1-SEI/#/./planning/project_planning?id=processo-de-design)). Outra coisa que faltou, padronização de acordo com os documentos que já estão no repositório. Cada parágrafo é escrito em HTML e não Markdown, além de estar faltando legendas das imagens e o lugar que as referências foram utilizadas no texto. Isso porque, se não foram realmente utilizadas é bibliografia e não referência.

Como se fazer um parágrafo:
```html
<p align = "justify"> &emsp;&emsp; Texto ...</p>
```

Como devem ser as legendas e imagens:
```html
<center><img src="caminho na máquina"></center>
<h6 align = "center">Figura X: sobre a figura ...</h6>
<h6 align = "center">Fonte: Da onde foi retirada ou se foi de autoria própria.</h6>
```

2021-08-12 16:47 UTC, Joao-Moura requested changes
Bem melhor, porém ainda tenho uns pontos a ressaltar.
Três  delas vou fazer logo por aqui porque se aplicam a todos os parágrafos
- Não quebrar linhas em um parágrafo, não tem problema deixar o parágrafo inteiro em uma linha só. Isso até facilita na review.
- Adicionar esse documento no mkdocs.yml, no seguinte formato (pf sempre teste antes no mkdocs, pq muitos erros podem ser evitados só usando o localhost)
```
[...]
- Planejamento:
    - Metodologia ...: "..."
    - Processo de Design: "planejamento/processoDeDesign.md"
[...]
```
- E por fim a imagem do processo de design está errado, o local deve ser
`../../images/planejamento/Processo-de-design-mayhew.png`

2021-08-12 16:47 UTC, Joao-Moura commented on docs/planejamento/processoDeDesign.md
> +i e os artefatos consumidos e produzidos em cada
Tem um i no início da frase

2021-08-12 16:47 UTC, Joao-Moura commented on docs/planejamento/processoDeDesign.md
> +projetada ou já aplicada à situação atual. Definindo: como executar cada atividade;
Esse parágrafo parece que foi retirado de alguma referência, pf adicionar ela. Se foi de outro projeto, coloque na referência de qual projeto foi retirado

2021-08-12 16:47 UTC, Joao-Moura commented on docs/planejamento/processoDeDesign.md
> +<p align = "justify"> &emsp;&emsp; O processo de design que será usado é o de Engenharia de Usabilidade de Mayhew. Pois, o processo consegue mostra de forma simples clara cada cada uma das etapas a s
Erro em "[...] mostra de forma simples clara [...]", adicionar ou uma vírgula ou um "e" (preferêncialmente o e)

2021-08-12 16:47 UTC, Joao-Moura commented on docs/planejamento/processoDeDesign.md
> +<p align = "justify">
faltou o `&emsp;&emsp` antes de iniciar o parágrafo

2021-08-12 16:47 UTC, Joao-Moura commented on docs/planejamento/processoDeDesign.md
> +princípios gerais de design de IHC.</p>
Apenas uma das fase do design foi citado, e as outras ?

2021-08-12 16:47 UTC, Joao-Moura commented on docs/planejamento/processoDeDesign.md
> +<h6 align = "center">Fonte: (BARBOSA, Simone; SILVA, Bruno. Interação Humano-Computador)
Em vez de colocar a referência direto colocar algo do tipo
"Figura retirada do livro Interação Humano-Computador de Barborsa _et al._ (Ano de publicação, pág que tem a foto se vc souber)."

2021-08-12 16:47 UTC, Joao-Moura commented on docs/planejamento/processoDeDesign.md
> +BARBOSA, Simone Diniz Junqueira; SILVA, Bruno Santana da; SILVEIRA, Milene Selbach; GASPARINI, Isabela; DARIN, Ticianne; BARBOSA, Gabriel Diniz Junqueira. Interação Humano-Computador e Experiência do
Padronizar a referência de acordo com o outros documento, cheque no de metodologias que lá existe um exemplo de como deve ser feito.

2021-08-13 14:01 UTC, Abraao1231 commented on docs/planejamento/processoDeDesign.md
> +projetada ou já aplicada à situação atual. Definindo: como executar cada atividade;
A referência usada foi o livro que está nas referencias.

2021-08-13 14:24 UTC, Abraao1231 commented
Foram resolvidos os problemas citados em relação a adição de conteúdo em relação ao processo de design, formatação correta dos parágrafos, referencias e imagens.

2021-08-13 15:02 UTC, Joao-Moura approved these changes
Show, agora sim ficou bom. Só uma última coisa é que vc falou que no parágrafo foi utilizado o livro da referência. Se possível adicionar o [1] que nem na legenda, só pra quem estiver lendo saber. De resto é isso, parabéns.

2021-08-13 20:11 UTC, fernandes-natanael approved these changes
Documentação está correto e bem organizada, exceto a referência. Acredito que traria mais organização se na referência você utiliza-se apenas o nome do primeiro autor seguido de et al., pois a ABNT aceita.
Segue link para ajuda na atualização: https://www.citethisforme.com/citation-generator/normas-abnt-referencing-guides

2021-08-14 17:05 UTC, merged